title: Tips and thoughts gathered throughout the years
description: About My Personal Coding Experience
author: Gheorghina Gligor
github: https://github.com/gheorghina
about: Thoughts on Coding, Software Architecture, Solving Business Problems, Growing as an Engineer and more importantly, growing as a Leader.
disqus_shortname: gheorghina-github-io
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/gheorghinab"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/gheorghina-gligor-2000a148/"
    - icon: fa-stack-exchange
      link: "https://www.goodreads.com/user/show/33537328-gheorghina"
    - icon: fa-github
      link: "https://github.com/gheorghina"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Bookshelf Recommendations
      url: /bookshelf_recommendations/
    - text: Learning Resources
      url: /learning_resources/
    - text: Mentorship Program for Staff Plus
      url: /mentorship/
    - text: Courses and Workshops
      url: /courses_workshops/

url: "https://gheorghina.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
