title: Useful Tips on Coding 
description: About My Personal Coding Experience
author: Gheorghina Gligor
github: https://github.com/gheorghina
about: Passionate Software Engineer. Fell in love with Elixir, did C#. Eager to learn new things while dragging others in the process. I love science, coffee & to travel
disqus_shortname: gheorghina-github-io
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/gheorghinab"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/gheorghina-gligor-2000a148/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/gheorghina"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://gheorghina.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
